/*
 * This file acts as a template for config.c that will be generated in the
 * kernel build directory after config(8) has been successfully run.
 *
 * $FreeBSD: releng/11.0/usr.sbin/config/kernconf.tmpl 169604 2007-05-16 16:08:04Z wkoszek $
 */
#include "opt_config.h"
#ifdef INCLUDE_CONFIG_FILE

/*
 * For !INCLUDE_CONFIG_FILE case, you should look at kern_mib.c. This is
 * where kernconfstring is defined then.
 */
const char kernconfstring[] __attribute__ ((section("kern_conf"))) =
"options	CONFIG_AUTOGENERATED\n\
ident	GENERIC\n\
machine	i386\n\
cpu	I686_CPU\n\
makeoptions	WITH_CTF=1\n\
makeoptions	DEBUG=-g\n\
options	USB_DEBUG\n\
options	SC_PIXEL_MODE\n\
options	VESA\n\
options	SMP\n\
options	RCTL\n\
options	RACCT_DEFAULT_TO_DISABLED\n\
options	RACCT\n\
options	INCLUDE_CONFIG_FILE\n\
options	DDB_CTF\n\
options	KDTRACE_HOOKS\n\
options	CAPABILITIES\n\
options	CAPABILITY_MODE\n\
options	AUDIT\n\
options	HWPMC_HOOKS\n\
options	KBD_INSTALL_CDEV\n\
options	PRINTF_BUFR_SIZE=128\n\
options	_KPOSIX_PRIORITY_SCHEDULING\n\
options	SYSVSEM\n\
options	SYSVMSG\n\
options	SYSVSHM\n\
options	STACK\n\
options	KTRACE\n\
options	SCSI_DELAY=5000\n\
options	COMPAT_FREEBSD10\n\
options	GEOM_LABEL\n\
options	GEOM_RAID\n\
options	GEOM_PART_GPT\n\
options	PSEUDOFS\n\
options	PROCFS\n\
options	CD9660\n\
options	MSDOSFS\n\
options	NFS_ROOT\n\
options	NFSLOCKD\n\
options	NFSD\n\
options	NFSCL\n\
options	MD_ROOT\n\
options	QUOTA\n\
options	UFS_GJOURNAL\n\
options	UFS_DIRHASH\n\
options	UFS_ACL\n\
options	SOFTUPDATES\n\
options	FFS\n\
options	SCTP\n\
options	TCP_OFFLOAD\n\
options	IPSEC\n\
options	INET6\n\
options	INET\n\
options	PREEMPTION\n\
options	SCHED_ULE\n\
options	MAXCPU=2\n\
options	KDB_TRACE\n\
options	KDB\n\
options	DDB\n\
options	GDB\n\
options	NEW_PCIB\n\
options	GEOM_PART_MBR\n\
options	GEOM_PART_EBR_COMPAT\n\
options	GEOM_PART_EBR\n\
options	GEOM_PART_BSD\n\
options	ISAPNP\n\
device	isa\n\
device	npx\n\
device	mem\n\
device	io\n\
device	uart_ns8250\n\
device	atpic\n\
device	apic\n\
device	cpufreq\n\
device	acpi\n\
device	pci\n\
device	ahci\n\
device	ata\n\
device	mvs\n\
device	siis\n\
device	scbus\n\
device	ch\n\
device	da\n\
device	cd\n\
device	pass\n\
device	ses\n\
device	atkbdc\n\
device	atkbd\n\
device	psm\n\
device	kbdmux\n\
device	vga\n\
device	splash\n\
device	sc\n\
device	pmtimer\n\
device	uart\n\
device	em\n\
device	miibus\n\
device	re\n\
device	loop\n\
device	random\n\
device	padlock_rng\n\
device	rdrand_rng\n\
device	ether\n\
device	vlan\n\
device	tun\n\
device	md\n\
device	gif\n\
device	firmware\n\
device	bpf\n\
device	uhci\n\
device	ohci\n\
device	ehci\n\
device	xhci\n\
device	usb\n\
device	ukbd\n\
device	umass\n\
device	sound\n\
device	snd_es137x\n\
device	vmx\n\
device	crypto\n\
";

#endif /* INCLUDE_CONFIG_FILE */
